alter table "public"."items" drop constraint "items_type_id_fkey";

alter table "public"."items" alter column "id" add generated by default as identity;

alter table "public"."items" alter column "id" set data type integer using "id"::integer;

CREATE UNIQUE INDEX categories_id_key ON public.categories USING btree (id);

CREATE UNIQUE INDEX items_id_key ON public.items USING btree (id);

alter table "public"."categories" add constraint "categories_id_key" UNIQUE using index "categories_id_key";

alter table "public"."items" add constraint "items_id_key" UNIQUE using index "items_id_key";

alter table "public"."types" add constraint "types_category_id_fkey" FOREIGN KEY (category_id) REFERENCES categories(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."types" validate constraint "types_category_id_fkey";

create policy "Enable insert for authenticated users only"
on "public"."categories"
as permissive
for all
to authenticated
using (true);


create policy "Enable insert for authenticated users only"
on "public"."items"
as permissive
for all
to authenticated
using (true);


create policy "Enable insert for authenticated users only"
on "public"."types"
as permissive
for all
to authenticated
using (true);



